name: Test

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./code

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.200'
 
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore 'SquidLib Testing.sln'
    
    - name: Test
      working-directory: ${{env.working-directory}}
      run: dotnet test --no-restore --verbosity normal --nologo 'SquidLib Testing.sln'
